### ISSUE TITLE
tambah filter Adblock ID

### ISSUE THREAD

**Issue by SuperMarioMakerII** [hillz2/openclash_adblock#1]
![Adblock ID](https://user-images.githubusercontent.com/60994762/173349587-d4160d4d-8b88-42ae-adcd-82588f1a1e00.png)

https://github.com/realodix/AdBlockID/issues
bro bisa tambah filter adblock ID ga soalnya di web indo banner nya apalagi situs judi masi blom keblock 
klo pake itu bnyak yg keblock

**Comment by hillz2** [comment]
Nggak bisa gan, Adblock di openclash bekerja di level DNS dengan cara block nama domain, sedangkan filter adblock ID campur, ada yang pakai nama domain ada yang bukan

![2022-06-13-190839_601x986_scrot](https://user-images.githubusercontent.com/25127225/173350668-2f52422d-5b98-415e-8087-c07110057a91.png)

**Comment by SuperMarioMakerII** [comment]
jadi solusinya pke adblocker apa bro di openwrt biar bisa bersih dr banner" dan iklan lainya kyk pke ublock origin atau adguard di browser. soalnya nnton youtube pke stb iklanya masi bisa muncul dan klo akses ke web banner" nya ngeselin bgt

**Comment by hillz2** [comment]
Semua adblock di openwrt cuman bisa blokir domain aja, nggak bisa blokir elemen html. Solusinya kalau di PC, tetep install ublock origin. Di HP install firefox + add on ublock origin untuk browsing, kalau mau nonton youtube pake youtube vanced.
