### ISSUE TITLE
nama rule provider abpindo di readme salah

### ISSUE THREAD

**Issue by karnadii** [hillz2/openclash_adblock#3]
di rule provider namanya `abpindo_annoyance` tapi di rules namanya `adblock_abpindo_annoyance`
![Screenshot 2022-12-03 041351](https://user-images.githubusercontent.com/18657277/205387153-ea0ddb10-ad37-49d5-88db-48214f947628.png)

**Comment by hillz2** [comment]
Sudah di fix. Thanks
